using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GeoPedia.Models
{
    [MetadataType(typeof(CountryMetadata))]
    public partial class Country
    {
        /// <summary>
        /// These meta or "buddy" classes are a workaround to the overwriten properties of your models generated by the framework.
        /// Notice that the parent class is a partial class of an already existing model, Country in this case, and the MetadataType annotation is pointing the partial class to another class. 
        /// </summary>
        class CountryMetadata
        {
            [Display(Name = "Country Code")]
            [Required(ErrorMessage = "Country code required")]
            [Remote("IsCodeAvailable", "Countries", ErrorMessage = "Country code already taken")]
            [StringLength(3, MinimumLength = 3, ErrorMessage = "Field must be exactly 3 characters")]
            public string Code
            {
                get
                {
                    return Code;
                }
                set
                {
                    Code = value.ToUpper();
                }
            }

            [Required]
            [Range(0, int.MaxValue)]
            public int Population { get; set; }

            [Required]
            public string Continent { get; set; }

            [Required]
            [Display(Name = "Country Name")]
            public string Name { get; set; }

            [DataType(DataType.Date)]
            [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
            public Nullable<DateTime> Established { get; set; }
        }
    }
}