//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoPedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Users
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string User_Role { get; set; }
    
        public virtual Site_Roles Site_Roles { get; set; }
    }
}
